services:
  db:
    image: postgres:18
    container_name: order-postgres
    ports:
      # info: postgreSQL desktop is already running on port:5432 needed to change it
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password@123
      POSTGRES_DB: order-service

    volumes:
      - ./postgresql:/data/postgres
