services:
  db:
    image: postgres:18
    container_name: inventory-postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password@123
      POSTGRES_DB: inventory-service

    volumes:
      - ./postgresql:/data/postgres
